version: 2

project_name: yeet

builds:
  - main: ./cmd/yeet
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/monkescience/yeet/internal/cli.buildVersion={{.Version}}
      - -X github.com/monkescience/yeet/internal/cli.buildCommit={{.ShortCommit}}
      - -X github.com/monkescience/yeet/internal/cli.buildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  disable: true

changelog:
  disable: true

release:
  mode: append
  replace_existing_artifacts: true

homebrew_casks:
  - repository:
      owner: monkescience
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
    commit_msg_template: "chore: update yeet to {{ .Tag }}"
    directory: Casks
    binaries:
      - yeet
    homepage: https://github.com/monkescience/yeet
    description: Automate releases based on conventional commits
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yeet"]
          end

scoops:
  - repository:
      owner: monkescience
      name: scoop-bucket
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
    commit_msg_template: "chore: update yeet to {{ .Tag }}"
    directory: bucket
    homepage: https://github.com/monkescience/yeet
    description: Automate releases based on conventional commits
    license: MIT
