defaultBaseImage: cgr.dev/chainguard/busybox:latest@sha256:7b11de6633c9bdcec128d10981f78fd7243d69029f27fdeb9ea87e42d45f8b35
defaultPlatforms:
  - linux/amd64
  - linux/arm64
defaultEnv:
  - CGO_ENABLED=0
builds:
  - id: yeet
    dir: .
    main: ./cmd/yeet
