defaultBaseImage: cgr.dev/chainguard/busybox:latest@sha256:54c9bc7645025a4d4ef686cb3d00b4e5416bf01d1243c6d3e7010fd222eb897f
defaultPlatforms:
  - linux/amd64
  - linux/arm64
defaultEnv:
  - CGO_ENABLED=0
builds:
  - id: yeet
    dir: .
    main: ./cmd/yeet
    ldflags:
      - -s -w
      - -X github.com/monkescience/yeet/internal/build.version={{.Env.VERSION}}
