defaultBaseImage: cgr.dev/chainguard/busybox:latest@sha256:705f999e817ad5d5cf7a0cc0b015844ed26ab9834d0735a8a1538dd05e654e3f
defaultPlatforms:
  - linux/amd64
  - linux/arm64
defaultEnv:
  - CGO_ENABLED=0
builds:
  - id: yeet
    dir: .
    main: ./cmd/yeet
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/monkescience/yeet/internal/build.version={{.Env.VERSION}}
