# yaml-language-server: $schema=https://raw.githubusercontent.com/monkescience/yeet/main/yeet.schema.json

version_files:
  - README.md

release:
  channels:
    beta:
      branch: beta
      prerelease: beta
    rc:
      branch: rc
      prerelease: rc

targets:
  yeet:
    type: path
    path: .
    tag_prefix: v
