package config_test

import (
	"context"
	"os"
	"testing"

	"github.com/monkescience/testastic"
	"github.com/monkescience/yeet/internal/config"
)

func TestDefault(t *testing.T) {
	t.Parallel()

	// given: nothing

	// when: creating a default config
	cfg := config.Default()

	// then: sensible defaults are set
	testastic.Equal(t, config.VersioningSemver, cfg.Versioning)
	testastic.Equal(t, "main", cfg.Branch)
	testastic.Equal(t, config.ProviderAuto, cfg.Provider)
	testastic.Equal(t, "origin", cfg.Repository.Remote)
	testastic.False(t, cfg.Release.SubjectIncludeBranch)
	testastic.False(t, cfg.Release.AutoMerge)
	testastic.False(t, cfg.Release.AutoMergeForce)
	testastic.Equal(t, config.AutoMergeMethodAuto, cfg.Release.AutoMergeMethod)
	testastic.Equal(t, 0, len(cfg.Release.Channels))
	testastic.Equal(t, "## ٩(^ᴗ^)۶ release created", cfg.Release.PRBodyHeader)
	testastic.Equal(
		t,
		"_Auto-generated preview — edit `CHANGELOG.md` to customize release notes._\n\n"+
			"_Made with [yeet](https://github.com/monkescience/yeet) - yeet it._",
		cfg.Release.PRBodyFooter,
	)
	testastic.Equal(t, 0, len(cfg.VersionFiles))
	testastic.Equal(t, "CHANGELOG.md", cfg.Changelog.File)
	testastic.Equal(t, 4, len(cfg.Changelog.Include))
	testastic.Equal(t, "YYYY.0M.MICRO", cfg.CalVer.Format)
	testastic.True(t, cfg.PreMajorBreakingBumpsMinor)
	testastic.True(t, cfg.PreMajorFeaturesBumpPatch)
	testastic.SliceEqual(t, []string{"feat"}, cfg.BumpTypes.Minor)
	testastic.SliceEqual(t, []string{"fix", "perf"}, cfg.BumpTypes.Patch)
}

func TestParse(t *testing.T) {
	t.Parallel()

	t.Run("valid minimal config", func(t *testing.T) {
		t.Parallel()

		// given: a minimal YAML config
		data, err := os.ReadFile("testdata/minimal/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: it succeeds with defaults filled in
		testastic.NoError(t, err)
		testastic.Equal(t, config.VersioningSemver, cfg.Versioning)
		testastic.Equal(t, "main", cfg.Branch)
	})

	t.Run("config with prerelease channels", func(t *testing.T) {
		t.Parallel()

		// given: a config with a prerelease channel
		data, err := os.ReadFile("testdata/prerelease_channels/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: channel settings are parsed and validated
		testastic.NoError(t, err)
		testastic.Equal(t, "beta", cfg.Release.Channels["beta"].Branch)
		testastic.Equal(t, "beta", cfg.Release.Channels["beta"].Prerelease)
	})

	t.Run("valid full config", func(t *testing.T) {
		t.Parallel()

		// given: a full YAML config
		data, err := os.ReadFile("testdata/full/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: all values are set correctly
		testastic.NoError(t, err)
		testastic.Equal(t, config.VersioningCalVer, cfg.Versioning)
		testastic.Equal(t, "develop", cfg.Branch)
		testastic.Equal(t, config.ProviderGitLab, cfg.Provider)
		testastic.Equal(t, "upstream", cfg.Repository.Remote)
		testastic.NotNil(t, cfg.Repository.GitLab)
		testastic.Equal(t, "gitlab.company.com", cfg.Repository.GitLab.Host)
		testastic.Equal(t, "group/subgroup/service", cfg.Repository.GitLab.Project)
		testastic.True(t, cfg.Release.SubjectIncludeBranch)
		testastic.True(t, cfg.Release.AutoMerge)
		testastic.True(t, cfg.Release.AutoMergeForce)
		testastic.Equal(t, config.AutoMergeMethodRebase, cfg.Release.AutoMergeMethod)
		testastic.Equal(t, "## Release checklist\n- [ ] smoke test", cfg.Release.PRBodyHeader)
		testastic.Equal(t, "_Generated by automation_", cfg.Release.PRBodyFooter)
		testastic.Equal(t, 2, len(cfg.VersionFiles))
		testastic.Equal(t, "VERSION", cfg.VersionFiles[0].Path)
		testastic.Equal(t, "CHANGES.md", cfg.Changelog.File)
		testastic.Equal(t, 2, len(cfg.Changelog.Include))
		testastic.Equal(t, "New Features", cfg.Changelog.Sections["feat"])
	})

	t.Run("config with json version file", func(t *testing.T) {
		t.Parallel()

		// given: a config that uses an explicit JSON version file entry
		data, err := os.ReadFile("testdata/json_version_file/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: the JSON entry is parsed with its explicit pointer
		testastic.NoError(t, err)
		testastic.Equal(t, 1, len(cfg.VersionFiles))
		testastic.Equal(t, "package.json", cfg.VersionFiles[0].Path)
		testastic.Equal(t, config.VersionFileFormatJSON, cfg.VersionFiles[0].Format)
		testastic.Equal(t, "/version", cfg.VersionFiles[0].JSONPointer)
	})

	t.Run("json version file requires json pointer", func(t *testing.T) {
		t.Parallel()

		// given: a JSON version file entry without an explicit pointer
		data, err := os.ReadFile("testdata/json_version_file_missing_pointer/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: validation rejects the ambiguous JSON entry
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "json_pointer")
	})

	t.Run("config with custom bump types", func(t *testing.T) {
		t.Parallel()

		// given: a config with custom bump_types
		data, err := os.ReadFile("testdata/custom_bump_types/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: bump types are parsed correctly
		testastic.NoError(t, err)
		testastic.SliceEqual(t, []string{"feat", "revert"}, cfg.BumpTypes.Minor)
		testastic.SliceEqual(t, []string{"fix", "perf", "docs"}, cfg.BumpTypes.Patch)
	})

	t.Run("config with changelog references", func(t *testing.T) {
		t.Parallel()

		// given: a config with changelog references
		data, err := os.ReadFile("testdata/changelog_references/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: references are parsed correctly
		testastic.NoError(t, err)
		testastic.Equal(t, 2, len(cfg.Changelog.References.Patterns))
		testastic.Equal(t, `JIRA-\d+`, cfg.Changelog.References.Patterns[0].Pattern)
		testastic.Equal(t, "https://jira.example.com/browse/{value}", cfg.Changelog.References.Patterns[0].URL)
		testastic.Equal(t, `#\d+`, cfg.Changelog.References.Patterns[1].Pattern)
		testastic.Equal(t, "", cfg.Changelog.References.Patterns[1].URL)
		testastic.Equal(t, 2, len(cfg.Changelog.References.Footers))
		testastic.Equal(t, "https://jira.example.com/browse/{value}", cfg.Changelog.References.Footers["Refs"])
		testastic.Equal(t, "", cfg.Changelog.References.Footers["Closes"])
	})

	t.Run("invalid versioning", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid versioning strategy
		data, err := os.ReadFile("testdata/invalid_versioning/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("invalid target versioning", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid target-level versioning strategy
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:       config.TargetTypePath,
				Path:       ".",
				TagPrefix:  "v",
				Versioning: config.VersioningStrategy("calendar"),
			},
		}

		// when: validating the config
		err := cfg.Validate(t.Context())

		// then: validation rejects the unsupported target versioning strategy
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.api.versioning")
	})

	t.Run("invalid provider", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid provider
		data, err := os.ReadFile("testdata/invalid_provider/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty string provider is invalid", func(t *testing.T) {
		t.Parallel()

		// given: config with the legacy empty-string provider value
		data, err := os.ReadFile("testdata/empty_provider/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty branch", func(t *testing.T) {
		t.Parallel()

		// given: config with empty branch
		data, err := os.ReadFile("testdata/empty_branch/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("repository sub-section must match provider", func(t *testing.T) {
		t.Parallel()

		// given: provider github with a gitlab sub-section
		data, err := os.ReadFile("testdata/invalid_repository_wrong_subsection/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: parsing rejects the mismatched sub-section
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.gitlab set but provider is github")
	})

	t.Run("provider auto rejects any repository sub-section", func(t *testing.T) {
		t.Parallel()

		// given: provider auto plus a github sub-section
		data, err := os.ReadFile("testdata/invalid_repository_auto_with_subsection/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: parsing rejects the sub-section under auto
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github set but provider is auto")
	})

	t.Run("azuredevops happy path parses and hydrates", func(t *testing.T) {
		t.Parallel()

		// given: provider azuredevops with a fully-populated sub-section
		data, err := os.ReadFile("testdata/valid_repository_azuredevops/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: parse succeeds and flat fields are hydrated from the sub-section
		testastic.NoError(t, err)
		testastic.Equal(t, config.ProviderAzureDevOps, cfg.Provider)
		testastic.NotNil(t, cfg.Repository.AzureDevOps)
		testastic.Equal(t, "dev.azure.com", cfg.Repository.AzureDevOps.Host)
		testastic.Equal(t, "contoso", cfg.Repository.AzureDevOps.Organization)
		testastic.Equal(t, "MyProject", cfg.Repository.AzureDevOps.Project)
		testastic.Equal(t, "yeet", cfg.Repository.AzureDevOps.Repo)
		testastic.Equal(t, "DefaultCollection", cfg.Repository.AzureDevOps.Collection)
	})

	t.Run("invalid yaml", func(t *testing.T) {
		t.Parallel()

		// given: invalid YAML syntax
		data := []byte("release: [")

		// when: parsing the config
		_, err := config.Parse(t.Context(), data)

		// then: parsing fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("targets require explicit tag prefix", func(t *testing.T) {
		t.Parallel()

		// given: a target config without per-target tag prefix
		data, err := os.ReadFile("testdata/targets_missing_prefix/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: target validation rejects the missing per-target prefix
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.api.tag_prefix must not be empty")
	})

	t.Run("explicit empty targets config is invalid", func(t *testing.T) {
		t.Parallel()

		// given: a YAML config that explicitly sets an empty targets map
		data, err := os.ReadFile("testdata/empty_targets/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(t.Context(), data)

		// then: validation rejects the empty targets block
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets must not be empty")
	})
}

func TestValidate(t *testing.T) {
	t.Parallel()

	t.Run("valid config passes", func(t *testing.T) {
		t.Parallel()

		// given: a valid default config with targets
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: no error
		testastic.NoError(t, err)
	})

	t.Run("empty changelog include fails", func(t *testing.T) {
		t.Parallel()

		// given: config with empty changelog include
		cfg := config.Default()
		cfg.Changelog.Include = nil

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty changelog file fails", func(t *testing.T) {
		t.Parallel()

		// given: config with empty changelog file
		cfg := config.Default()
		cfg.Changelog.File = ""

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty version file path fails", func(t *testing.T) {
		t.Parallel()

		// given: config with an empty version file path
		cfg := config.Default()
		cfg.VersionFiles = []config.VersionFile{{Path: "  "}}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("invalid auto merge method fails", func(t *testing.T) {
		t.Parallel()

		// given: config with unsupported auto merge method
		cfg := config.Default()
		cfg.Release.AutoMergeMethod = "fast-forward"

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("repository owner and repo must be set together", func(t *testing.T) {
		t.Parallel()

		// given: github sub-section with only owner set
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Owner: "platform"}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("repository project must match owner and repo when both are set", func(t *testing.T) {
		t.Parallel()

		// given: github sub-section with conflicting explicit coordinates
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{
			Owner:   "platform",
			Repo:    "yeet",
			Project: "other/yeet",
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.project must match repository.github.owner/repo")
	})

	t.Run("github project must stay in owner repo form", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with a subgroup-style project path
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Project: "group/subgroup/service"}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.project must be in owner/repo form")
	})

	t.Run("github project in valid owner repo form passes", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with a valid two-segment project
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Project: "owner/repo"}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: no error
		testastic.NoError(t, err)
	})

	t.Run("github project with empty owner segment fails", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with an empty owner segment
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Project: "/repo"}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.project must be in owner/repo form")
	})

	t.Run("github project with empty repo segment fails", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with an empty repo segment
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Project: "owner/"}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.project must be in owner/repo form")
	})

	t.Run("empty repository remote fails", func(t *testing.T) {
		t.Parallel()

		// given: repository config with an empty remote name
		cfg := config.Default()
		cfg.Repository.Remote = ""

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("windows drive letter target path fails", func(t *testing.T) {
		t.Parallel()

		// given: a target with an absolute Windows-style path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "C:/repo/app",
				TagPrefix: "api-v",
			},
		}

		// when: validating the config
		err := cfg.Validate(t.Context())

		// then: the repo-relative path validation rejects the absolute path
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be repo-relative")
	})

	t.Run("windows drive letter exclude path fails", func(t *testing.T) {
		t.Parallel()

		// given: a target with an absolute Windows-style exclude path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"root": {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api", "D:/repo/shared"},
				Includes:     []string{"api"},
			},
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
		}

		// when: validating the config
		err := cfg.Validate(t.Context())

		// then: the repo-relative path validation rejects the absolute exclude path
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be repo-relative")
	})

	t.Run("duplicate inherited version file across targets fails", func(t *testing.T) {
		t.Parallel()

		// given: multiple targets that inherit the same top-level version file path
		cfg := config.Default()
		cfg.VersionFiles = []config.VersionFile{{Path: "VERSION"}}
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
				Changelog: config.ChangelogConfig{File: "services/api/CHANGELOG.md"},
			},
			"web": {
				Type:      config.TargetTypePath,
				Path:      "apps/web",
				TagPrefix: "web-v",
				Changelog: config.ChangelogConfig{File: "apps/web/CHANGELOG.md"},
			},
		}

		// when: validating the config
		err := cfg.Validate(t.Context())

		// then: validation rejects the shared version file ownership before release time
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "version_files")
	})

	t.Run("overlapping bump types fails", func(t *testing.T) {
		t.Parallel()

		// given: config with a type appearing in both minor and patch
		cfg := config.Default()
		cfg.BumpTypes.Minor = []string{"feat"}
		cfg.BumpTypes.Patch = []string{"fix", "feat"}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "feat")
	})

	t.Run("empty string in bump types minor fails", func(t *testing.T) {
		t.Parallel()

		// given: config with an empty string in bump_types.minor
		cfg := config.Default()
		cfg.BumpTypes.Minor = []string{"feat", ""}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "bump_types.minor")
	})

	t.Run("empty bump types lists are valid", func(t *testing.T) {
		t.Parallel()

		// given: config with empty bump type lists
		cfg := config.Default()
		cfg.BumpTypes.Minor = []string{}
		cfg.BumpTypes.Patch = []string{}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation passes
		testastic.NoError(t, err)
	})

	t.Run("blank repository host fails", func(t *testing.T) {
		t.Parallel()

		// given: github sub-section with host set to whitespace only
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Host: "   ", Owner: "o", Repo: "r"}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation rejects the blank host
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.host")
	})

	t.Run("blank repository owner fails", func(t *testing.T) {
		t.Parallel()

		// given: github sub-section with owner set to whitespace only
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Owner: "   "}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation rejects the blank owner
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.owner")
	})

	t.Run("blank repository repo fails", func(t *testing.T) {
		t.Parallel()

		// given: github sub-section with repo set to whitespace only
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Repo: "   "}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation rejects the blank repo
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.repo")
	})

	t.Run("blank repository project fails", func(t *testing.T) {
		t.Parallel()

		// given: gitlab sub-section with project set to whitespace only
		cfg := config.Default()
		cfg.Provider = config.ProviderGitLab
		cfg.Repository.GitLab = &config.GitLabRepositoryConfig{Project: "   "}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation rejects the blank project
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.gitlab.project")
	})

	t.Run("github owner with slash fails", func(t *testing.T) {
		t.Parallel()

		// given: github provider with subgroup-style owner
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{Owner: "group/sub", Repo: "service"}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: github does not allow nested owner paths
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.owner")
	})

	t.Run("repository project must match owner and repo when project is owner-repo style", func(t *testing.T) {
		t.Parallel()

		// given: github sub-section where project does not equal owner/repo
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.GitHub = &config.GitHubRepositoryConfig{
			Owner:   "platform",
			Repo:    "yeet",
			Project: "platform/other",
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: mismatch is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.github.project must match")
	})

	t.Run("release channel name must not be empty", func(t *testing.T) {
		t.Parallel()

		// given: a channel with a whitespace-only name
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"   ": {Branch: "beta", Prerelease: "beta"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty channel name is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "release.channels")
	})

	t.Run("release channel name stable is reserved", func(t *testing.T) {
		t.Parallel()

		// given: a channel named "stable" (case-insensitive)
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"Stable": {Branch: "release", Prerelease: "rc"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: reserved name is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "stable")
	})

	t.Run("release channel branch must not be empty", func(t *testing.T) {
		t.Parallel()

		// given: a channel with an empty branch
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"beta": {Branch: "   ", Prerelease: "beta"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty branch is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "branch must not be empty")
	})

	t.Run("release channels with duplicate branches fails", func(t *testing.T) {
		t.Parallel()

		// given: two channels pointing at the same branch
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"alpha": {Branch: "release", Prerelease: "alpha"},
			"beta":  {Branch: "release", Prerelease: "beta"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: duplicate branch is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "duplicates")
	})

	t.Run("release channel prerelease must not be empty", func(t *testing.T) {
		t.Parallel()

		// given: a channel with an empty prerelease identifier
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"beta": {Branch: "beta", Prerelease: "   "},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty prerelease is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "prerelease must not be empty")
	})

	t.Run("release channel invalid prerelease identifier fails", func(t *testing.T) {
		t.Parallel()

		// given: a channel with a prerelease identifier semver rejects
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"beta": {Branch: "beta", Prerelease: "not valid!"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: invalid identifier is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "prerelease")
	})

	t.Run("release channels with duplicate prerelease identifiers fails", func(t *testing.T) {
		t.Parallel()

		// given: two channels with the same prerelease identifier
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"alpha": {Branch: "alpha", Prerelease: "rc"},
			"beta":  {Branch: "beta", Prerelease: "rc"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: duplicate prerelease identifier is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "duplicates")
	})

	t.Run("release channel branch must not duplicate stable branch", func(t *testing.T) {
		t.Parallel()

		// given: a channel branch that collides with the stable branch
		cfg := config.Default()
		cfg.Branch = "main"
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}
		cfg.Release.Channels = map[string]config.ReleaseChannelConfig{
			"beta": {Branch: "main", Prerelease: "beta"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: stable-branch collision is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "duplicates stable branch")
	})

	t.Run("duplicate target tag prefix fails", func(t *testing.T) {
		t.Parallel()

		// given: two targets sharing a tag prefix
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "v",
			},
			"web": {
				Type:      config.TargetTypePath,
				Path:      "apps/web",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: shared tag prefix is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "tag_prefix")
	})

	t.Run("derived target with unknown include fails", func(t *testing.T) {
		t.Parallel()

		// given: a derived target referencing a non-existent target
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"root": {
				Type:      config.TargetTypeDerived,
				Path:      ".",
				TagPrefix: "v",
				Includes:  []string{"missing"},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: unknown include is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "does not refer to a defined target")
	})

	t.Run("derived target including derived target fails", func(t *testing.T) {
		t.Parallel()

		// given: a derived target whose include is itself derived
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"inner": {
				Type:      config.TargetTypeDerived,
				Path:      "services",
				TagPrefix: "inner-v",
				Includes:  []string{"leaf"},
			},
			"leaf": {
				Type:      config.TargetTypePath,
				Path:      "services/leaf",
				TagPrefix: "leaf-v",
			},
			"outer": {
				Type:      config.TargetTypeDerived,
				Path:      ".",
				TagPrefix: "v",
				Includes:  []string{"inner"},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: derived-of-derived include is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must refer to a path target")
	})

	t.Run("target with empty type fails", func(t *testing.T) {
		t.Parallel()

		// given: a target without a type
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: missing target type is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.app.type")
	})

	t.Run("target with empty id fails", func(t *testing.T) {
		t.Parallel()

		// given: a target keyed under whitespace
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"   ": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty target ID is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "target IDs")
	})

	t.Run("path target with empty path fails", func(t *testing.T) {
		t.Parallel()

		// given: a path target with no path set
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty path is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "path must not be empty")
	})

	t.Run("path target with includes fails", func(t *testing.T) {
		t.Parallel()

		// given: a path target that also lists includes
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
				Includes:  []string{"web"},
			},
			"web": {
				Type:      config.TargetTypePath,
				Path:      "apps/web",
				TagPrefix: "web-v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: includes on a path target are rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "includes is only valid for derived targets")
	})

	t.Run("derived target with no includes fails", func(t *testing.T) {
		t.Parallel()

		// given: a derived target without includes
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"root": {
				Type:      config.TargetTypeDerived,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty includes is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "includes must not be empty")
	})

	t.Run("target with empty version_files entry fails", func(t *testing.T) {
		t.Parallel()

		// given: a target whose version_files contains an empty path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:         config.TargetTypePath,
				Path:         ".",
				TagPrefix:    "v",
				VersionFiles: []config.VersionFile{{Path: "  "}},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty version_files entry is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "version_files")
	})

	t.Run("target with empty changelog file fails", func(t *testing.T) {
		t.Parallel()

		// given: a target overriding changelog file to empty
		cfg := config.Default()
		cfg.Changelog.File = ""
		cfg.Changelog.Include = nil
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating (top-level changelog blocks before target reaches its check)
		err := cfg.Validate(t.Context())

		// then: top-level changelog.file empty error first
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "changelog.file")
	})

	t.Run("target inherits empty top-level changelog include is rejected", func(t *testing.T) {
		t.Parallel()

		// given: a target inheriting an empty top-level changelog include list
		cfg := config.Default()
		cfg.Changelog.Include = nil
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation rejects the empty include
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "changelog.include")
	})

	t.Run("target with relative parent path fails", func(t *testing.T) {
		t.Parallel()

		// given: a target whose path escapes the repo
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: "../outside", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: parent paths are rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be repo-relative")
	})

	t.Run("target with absolute slash path fails", func(t *testing.T) {
		t.Parallel()

		// given: a target with an absolute Unix-style path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: "/etc/yeet", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: absolute path is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be repo-relative")
	})

	t.Run("target with empty path string fails", func(t *testing.T) {
		t.Parallel()

		// given: a target whose path is whitespace only
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: "   ", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: blank path is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must not be empty")
	})

	t.Run("exclude path outside target path fails", func(t *testing.T) {
		t.Parallel()

		// given: a non-root target with an exclude path that is not inside it
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:         config.TargetTypePath,
				Path:         "services/api",
				TagPrefix:    "api-v",
				ExcludePaths: []string{"services/web"},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: excludes outside the target are rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be inside")
	})

	t.Run("exclude path with parent traversal fails", func(t *testing.T) {
		t.Parallel()

		// given: an exclude path that escapes the repo via ".."
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:         config.TargetTypePath,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"../outside"},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: parent traversal is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "exclude_paths")
	})

	t.Run("exclude path empty entry fails", func(t *testing.T) {
		t.Parallel()

		// given: an exclude path entry that normalizes to empty
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:         config.TargetTypePath,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"   "},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: empty exclude entry is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "exclude_paths")
	})
}

func TestBumpTypesConfig_ToBumpMapping(t *testing.T) {
	t.Parallel()

	t.Run("default config produces default mapping", func(t *testing.T) {
		t.Parallel()

		// given: default bump types config
		bt := config.BumpTypesConfig{
			Minor: []string{"feat"},
			Patch: []string{"fix", "perf"},
		}

		// when: converting to bump mapping
		mapping := bt.ToBumpMapping()

		// then: matches expected mapping
		testastic.Equal(t, 3, len(mapping))
		testastic.Equal(t, "minor", mapping["feat"])
		testastic.Equal(t, "patch", mapping["fix"])
		testastic.Equal(t, "patch", mapping["perf"])
	})

	t.Run("custom config produces custom mapping", func(t *testing.T) {
		t.Parallel()

		// given: custom bump types config
		bt := config.BumpTypesConfig{
			Minor: []string{"feat", "revert"},
			Patch: []string{"docs"},
		}

		// when: converting to bump mapping
		mapping := bt.ToBumpMapping()

		// then: matches expected mapping
		testastic.Equal(t, 3, len(mapping))
		testastic.Equal(t, "minor", mapping["feat"])
		testastic.Equal(t, "minor", mapping["revert"])
		testastic.Equal(t, "patch", mapping["docs"])
	})

	t.Run("empty config produces empty mapping", func(t *testing.T) {
		t.Parallel()

		// given: empty bump types config
		bt := config.BumpTypesConfig{}

		// when: converting to bump mapping
		mapping := bt.ToBumpMapping()

		// then: empty mapping
		testastic.Equal(t, 0, len(mapping))
	})
}

func TestResolvedTargets(t *testing.T) {
	t.Parallel()

	t.Run("resolves monorepo targets with inherited defaults", func(t *testing.T) {
		t.Parallel()

		// given: a monorepo config with path and derived targets
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"root": {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api"},
				Includes:     []string{"api"},
			},
		}

		// when: resolving targets
		resolvedTargets, err := cfg.ResolvedTargets(t.Context())

		// then: target defaults and ownership data are expanded correctly
		testastic.NoError(t, err)
		testastic.Equal(t, "api-v", resolvedTargets["api"].TagPrefix)
		testastic.Equal(t, config.VersioningSemver, resolvedTargets["api"].Versioning)
		testastic.Equal(t, "CHANGELOG.md", resolvedTargets["root"].Changelog.File)
		testastic.SliceEqual(t, []string{"api"}, resolvedTargets["root"].Includes)
	})

	t.Run("normalizes target ids for lookup and includes", func(t *testing.T) {
		t.Parallel()

		// given: targets whose YAML IDs include surrounding whitespace
		cfg := config.Default()
		spacedAPIID := " api "
		spacedRootID := " root "
		cfg.Targets = map[string]config.Target{
			spacedAPIID: {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			spacedRootID: {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api"},
				Includes:     []string{spacedAPIID},
			},
		}

		// when: resolving targets
		resolvedTargets, err := cfg.ResolvedTargets(t.Context())

		// then: normalized IDs are used consistently
		testastic.NoError(t, err)
		testastic.Equal(t, "api", resolvedTargets["api"].ID)
		testastic.Equal(t, "root", resolvedTargets["root"].ID)
		testastic.SliceEqual(t, []string{"api"}, resolvedTargets["root"].Includes)
	})

	t.Run("rejects duplicate normalized target ids", func(t *testing.T) {
		t.Parallel()

		// given: two target IDs that normalize to the same value
		cfg := config.Default()
		spacedAPIID := " api "
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			spacedAPIID: {
				Type:      config.TargetTypePath,
				Path:      "services/api-alt",
				TagPrefix: "api-alt-v",
			},
		}

		// when: resolving targets
		_, err := cfg.ResolvedTargets(t.Context())

		// then: validation rejects the duplicate logical ID
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "target IDs must be unique and non-empty")
	})

	t.Run("rejects overlapping direct ownership", func(t *testing.T) {
		t.Parallel()

		// given: two path targets that directly overlap
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"services": {
				Type:      config.TargetTypePath,
				Path:      "services",
				TagPrefix: "services-v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: ambiguous ownership is rejected
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "direct path ownership overlaps")
	})
}

func TestPreMajorOptions(t *testing.T) {
	t.Parallel()

	t.Run("parses explicit false at top level", func(t *testing.T) {
		t.Parallel()

		// given: a config with both pre-major options explicitly false
		data, err := os.ReadFile("testdata/pre_major_explicit_false/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(t.Context(), data)

		// then: both options are false
		testastic.NoError(t, err)
		testastic.False(t, cfg.PreMajorBreakingBumpsMinor)
		testastic.False(t, cfg.PreMajorFeaturesBumpPatch)
	})

	t.Run("target inherits top-level values", func(t *testing.T) {
		t.Parallel()

		// given: top-level options set to false, target does not override
		cfg := config.Default()
		cfg.PreMajorBreakingBumpsMinor = false
		cfg.PreMajorFeaturesBumpPatch = false
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target inherits top-level values
		testastic.NoError(t, err)
		testastic.False(t, resolved["app"].PreMajorBreakingBumpsMinor)
		testastic.False(t, resolved["app"].PreMajorFeaturesBumpPatch)
	})

	t.Run("target overrides top-level true with false", func(t *testing.T) {
		t.Parallel()

		// given: top-level defaults are true, target sets false
		cfg := config.Default()
		breakingFalse := false
		featuresFalse := false
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                       config.TargetTypePath,
				Path:                       ".",
				TagPrefix:                  "v",
				PreMajorBreakingBumpsMinor: &breakingFalse,
				PreMajorFeaturesBumpPatch:  &featuresFalse,
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target overrides with false
		testastic.NoError(t, err)
		testastic.False(t, resolved["app"].PreMajorBreakingBumpsMinor)
		testastic.False(t, resolved["app"].PreMajorFeaturesBumpPatch)
	})

	t.Run("target overrides top-level false with true", func(t *testing.T) {
		t.Parallel()

		// given: top-level set to false, target overrides with true
		cfg := config.Default()
		cfg.PreMajorBreakingBumpsMinor = false
		cfg.PreMajorFeaturesBumpPatch = false
		breakingTrue := true
		featuresTrue := true
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                       config.TargetTypePath,
				Path:                       ".",
				TagPrefix:                  "v",
				PreMajorBreakingBumpsMinor: &breakingTrue,
				PreMajorFeaturesBumpPatch:  &featuresTrue,
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target overrides with true
		testastic.NoError(t, err)
		testastic.True(t, resolved["app"].PreMajorBreakingBumpsMinor)
		testastic.True(t, resolved["app"].PreMajorFeaturesBumpPatch)
	})

	t.Run("target inherits top-level references and merges overrides", func(t *testing.T) {
		t.Parallel()

		// given: top-level references with patterns and footers, target adds a footer override
		cfg := config.Default()
		cfg.Changelog.References = config.ReferencesConfig{
			Patterns: []config.ReferencePattern{
				{Pattern: `JIRA-\d+`, URL: "https://jira.example.com/browse/{value}"},
			},
			Footers: map[string]string{
				"Refs": "https://jira.example.com/browse/{value}",
			},
		}
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				Changelog: config.ChangelogConfig{
					References: config.ReferencesConfig{
						Footers: map[string]string{
							"Closes": "",
						},
					},
				},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target inherits top-level patterns (no override) and merges footers
		testastic.NoError(t, err)
		testastic.Equal(t, 1, len(resolved["app"].Changelog.References.Patterns))
		testastic.Equal(t, `JIRA-\d+`, resolved["app"].Changelog.References.Patterns[0].Pattern)
		testastic.Equal(t, 2, len(resolved["app"].Changelog.References.Footers))
		testastic.Equal(t, "https://jira.example.com/browse/{value}", resolved["app"].Changelog.References.Footers["Refs"])
		testastic.Equal(t, "", resolved["app"].Changelog.References.Footers["Closes"])
	})

	t.Run("rejects pre_major_breaking_bumps_minor on calver target", func(t *testing.T) {
		t.Parallel()

		// given: a calver target with explicit pre_major_breaking_bumps_minor
		cfg := config.Default()
		breakingTrue := true
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                       config.TargetTypePath,
				Path:                       ".",
				TagPrefix:                  "v",
				Versioning:                 config.VersioningCalVer,
				PreMajorBreakingBumpsMinor: &breakingTrue,
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: error mentions the incompatibility
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "pre_major_breaking_bumps_minor")
		testastic.ErrorContains(t, err, "calver")
	})

	t.Run("rejects pre_major_features_bump_patch on calver target", func(t *testing.T) {
		t.Parallel()

		// given: a calver target with explicit pre_major_features_bump_patch
		cfg := config.Default()
		featuresFalse := false
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                      config.TargetTypePath,
				Path:                      ".",
				TagPrefix:                 "v",
				Versioning:                config.VersioningCalVer,
				PreMajorFeaturesBumpPatch: &featuresFalse,
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: error mentions the incompatibility
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "pre_major_features_bump_patch")
		testastic.ErrorContains(t, err, "calver")
	})

	t.Run("allows calver target without pre_major overrides", func(t *testing.T) {
		t.Parallel()

		// given: a calver target that inherits pre_major options (does not set them)
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: no error, inherited options are silently ignored
		testastic.NoError(t, err)
	})

	t.Run("rejects invalid top-level calver format", func(t *testing.T) {
		t.Parallel()

		// given: a config with an unsupported calver format
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.CalVer.Format = "YYYY.QQ.MICRO"
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails before release planning
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "calver.format")
	})

	t.Run("rejects invalid target calver format", func(t *testing.T) {
		t.Parallel()

		// given: a target with an unsupported calver format override
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				CalVer: config.CalVerConfig{
					Format: "YYYY.0M",
				},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation fails with the target path
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.app.calver.format")
	})
}

func TestLoad(t *testing.T) {
	t.Parallel()

	t.Run("missing file returns wrapped read error", func(t *testing.T) {
		t.Parallel()

		// given: a path that does not exist
		path := "testdata/does_not_exist.yaml"

		// when: loading the config
		_, err := config.Load(context.Background(), path)

		// then: load returns a contextual error
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "read config file")
	})

	t.Run("loads valid file from disk", func(t *testing.T) {
		t.Parallel()

		// given: a path to a known-good fixture
		path := "testdata/minimal/input.yaml"

		// when: loading the config
		cfg, err := config.Load(context.Background(), path)

		// then: it succeeds
		testastic.NoError(t, err)
		testastic.Equal(t, config.VersioningSemver, cfg.Versioning)
	})
}

func TestResolvedTargets_Merging(t *testing.T) {
	t.Parallel()

	t.Run("target overrides changelog file path", func(t *testing.T) {
		t.Parallel()

		// given: a target overriding the top-level changelog file path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				Changelog: config.ChangelogConfig{
					File: "docs/RELEASES.md",
				},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target uses the override
		testastic.NoError(t, err)
		testastic.Equal(t, "docs/RELEASES.md", resolved["app"].Changelog.File)
	})

	t.Run("target overrides changelog include list", func(t *testing.T) {
		t.Parallel()

		// given: a target overriding the include list
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				Changelog: config.ChangelogConfig{
					Include: []string{"feat", "fix"},
				},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: include is replaced (not merged)
		testastic.NoError(t, err)
		testastic.SliceEqual(t, []string{"feat", "fix"}, resolved["app"].Changelog.Include)
	})

	t.Run("target merges changelog sections over defaults", func(t *testing.T) {
		t.Parallel()

		// given: a target overriding only one section label
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				Changelog: config.ChangelogConfig{
					Sections: map[string]string{"feat": "Shiny New Things"},
				},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target keeps inherited sections and overrides only the specified one
		testastic.NoError(t, err)
		testastic.Equal(t, "Shiny New Things", resolved["app"].Changelog.Sections["feat"])
		testastic.Equal(t, "Bug Fixes", resolved["app"].Changelog.Sections["fix"])
	})

	t.Run("target overrides reference patterns", func(t *testing.T) {
		t.Parallel()

		// given: top-level patterns and a target with its own pattern list
		cfg := config.Default()
		cfg.Changelog.References = config.ReferencesConfig{
			Patterns: []config.ReferencePattern{{Pattern: `JIRA-\d+`, URL: "https://jira/{value}"}},
			Footers:  map[string]string{"Refs": "https://jira/{value}"},
		}
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				Changelog: config.ChangelogConfig{
					References: config.ReferencesConfig{
						Patterns: []config.ReferencePattern{{Pattern: `#\d+`, URL: ""}},
					},
				},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target patterns replace the inherited list and footers stay inherited
		testastic.NoError(t, err)
		testastic.Equal(t, 1, len(resolved["app"].Changelog.References.Patterns))
		testastic.Equal(t, `#\d+`, resolved["app"].Changelog.References.Patterns[0].Pattern)
		testastic.Equal(t, "https://jira/{value}", resolved["app"].Changelog.References.Footers["Refs"])
	})

	t.Run("target overrides calver format", func(t *testing.T) {
		t.Parallel()

		// given: a calver target overriding the top-level format
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:       config.TargetTypePath,
				Path:       ".",
				TagPrefix:  "v",
				Versioning: config.VersioningCalVer,
				CalVer:     config.CalVerConfig{Format: "YYYY.MM.MICRO"},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target keeps its own format
		testastic.NoError(t, err)
		testastic.Equal(t, "YYYY.MM.MICRO", resolved["app"].CalVer.Format)
	})

	t.Run("target overrides version_files entirely", func(t *testing.T) {
		t.Parallel()

		// given: top-level version files and a target overriding them
		cfg := config.Default()
		cfg.VersionFiles = []config.VersionFile{{Path: "VERSION"}}
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:         config.TargetTypePath,
				Path:         ".",
				TagPrefix:    "v",
				VersionFiles: []config.VersionFile{{Path: "package.json"}},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target uses its own list (not merged)
		testastic.NoError(t, err)
		testastic.Equal(t, "package.json", resolved["app"].VersionFiles[0].Path)
	})

	t.Run("target inherits top-level versioning when unset", func(t *testing.T) {
		t.Parallel()

		// given: top-level set to calver, target leaves versioning unset
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: target inherits calver
		testastic.NoError(t, err)
		testastic.Equal(t, config.VersioningCalVer, resolved["app"].Versioning)
	})

	t.Run("target tag prefix is trimmed", func(t *testing.T) {
		t.Parallel()

		// given: a tag prefix with surrounding whitespace
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "  v  ",
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: tag prefix is normalized
		testastic.NoError(t, err)
		testastic.Equal(t, "v", resolved["app"].TagPrefix)
	})

	t.Run("normalizes nested target path slashes", func(t *testing.T) {
		t.Parallel()

		// given: a target path with redundant separators
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services//api/",
				TagPrefix: "api-v",
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets(t.Context())

		// then: path is cleaned
		testastic.NoError(t, err)
		testastic.Equal(t, "services/api", resolved["api"].Path)
	})

	t.Run("derived target with non-overlapping include skips ownership conflict", func(t *testing.T) {
		t.Parallel()

		// given: a derived target whose included path is excluded
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"root": {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api"},
				Includes:     []string{"api"},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: ownership is unambiguous
		testastic.NoError(t, err)
	})

	t.Run("derived target without exclude overlapping included path fails", func(t *testing.T) {
		t.Parallel()

		// given: a derived root target that does not exclude the included path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"root": {
				Type:      config.TargetTypeDerived,
				Path:      ".",
				TagPrefix: "v",
				Includes:  []string{"api"},
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: overlap with the include is rejected
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "direct path ownership overlaps")
	})

	t.Run("disjoint targets do not overlap", func(t *testing.T) {
		t.Parallel()

		// given: two targets in unrelated paths
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"web": {
				Type:      config.TargetTypePath,
				Path:      "apps/web",
				TagPrefix: "web-v",
			},
		}

		// when: validating
		err := cfg.Validate(t.Context())

		// then: validation passes
		testastic.NoError(t, err)
	})
}

func TestRepoPathContains(t *testing.T) {
	t.Parallel()

	// given: a base path and candidates with various relationships
	cases := map[string]struct {
		base, candidate string
		want            bool
	}{
		"root contains everything":  {".", "anything", true},
		"identical paths":           {"services/api", "services/api", true},
		"prefix containment":        {"services", "services/api", true},
		"prefix substring no match": {"service", "services/api", false},
		"unrelated paths":           {"apps", "services/api", false},
		"candidate above base":      {"services/api", "services", false},
	}

	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			// when: checking containment
			got := config.RepoPathContains(tc.base, tc.candidate)

			// then: result matches expectation
			testastic.Equal(t, tc.want, got)
		})
	}
}
