package config_test

import (
	"os"
	"testing"

	"github.com/monkescience/testastic"
	"github.com/monkescience/yeet/internal/config"
)

func TestDefault(t *testing.T) {
	t.Parallel()

	// given: nothing

	// when: creating a default config
	cfg := config.Default()

	// then: sensible defaults are set
	testastic.Equal(t, config.VersioningSemver, cfg.Versioning)
	testastic.Equal(t, "main", cfg.Branch)
	testastic.Equal(t, config.ProviderAuto, cfg.Provider)
	testastic.Equal(t, "origin", cfg.Repository.Remote)
	testastic.False(t, cfg.Release.SubjectIncludeBranch)
	testastic.False(t, cfg.Release.AutoMerge)
	testastic.False(t, cfg.Release.AutoMergeForce)
	testastic.Equal(t, config.AutoMergeMethodAuto, cfg.Release.AutoMergeMethod)
	testastic.Equal(t, "## ٩(^ᴗ^)۶ release created", cfg.Release.PRBodyHeader)
	testastic.Equal(t, "_Made with [yeet](https://github.com/monkescience/yeet) - yeet it._", cfg.Release.PRBodyFooter)
	testastic.Equal(t, 0, len(cfg.VersionFiles))
	testastic.Equal(t, "CHANGELOG.md", cfg.Changelog.File)
	testastic.Equal(t, 4, len(cfg.Changelog.Include))
	testastic.Equal(t, "YYYY.0M.MICRO", cfg.CalVer.Format)
	testastic.True(t, cfg.PreMajorBreakingBumpsMinor)
	testastic.True(t, cfg.PreMajorFeaturesBumpPatch)
	testastic.SliceEqual(t, []string{"feat"}, cfg.BumpTypes.Minor)
	testastic.SliceEqual(t, []string{"fix", "perf"}, cfg.BumpTypes.Patch)
}

func TestParse(t *testing.T) {
	t.Parallel()

	t.Run("valid minimal config", func(t *testing.T) {
		t.Parallel()

		// given: a minimal YAML config
		data, err := os.ReadFile("testdata/minimal/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(data)

		// then: it succeeds with defaults filled in
		testastic.NoError(t, err)
		testastic.Equal(t, config.VersioningSemver, cfg.Versioning)
		testastic.Equal(t, "main", cfg.Branch)
	})

	t.Run("valid full config", func(t *testing.T) {
		t.Parallel()

		// given: a full YAML config
		data, err := os.ReadFile("testdata/full/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(data)

		// then: all values are set correctly
		testastic.NoError(t, err)
		testastic.Equal(t, config.VersioningCalVer, cfg.Versioning)
		testastic.Equal(t, "develop", cfg.Branch)
		testastic.Equal(t, config.ProviderGitLab, cfg.Provider)
		testastic.Equal(t, "upstream", cfg.Repository.Remote)
		testastic.Equal(t, "gitlab.company.com", cfg.Repository.Host)
		testastic.Equal(t, "group/subgroup/service", cfg.Repository.Project)
		testastic.True(t, cfg.Release.SubjectIncludeBranch)
		testastic.True(t, cfg.Release.AutoMerge)
		testastic.True(t, cfg.Release.AutoMergeForce)
		testastic.Equal(t, config.AutoMergeMethodRebase, cfg.Release.AutoMergeMethod)
		testastic.Equal(t, "## Release checklist\n- [ ] smoke test", cfg.Release.PRBodyHeader)
		testastic.Equal(t, "_Generated by automation_", cfg.Release.PRBodyFooter)
		testastic.Equal(t, 2, len(cfg.VersionFiles))
		testastic.Equal(t, "VERSION", cfg.VersionFiles[0])
		testastic.Equal(t, "CHANGES.md", cfg.Changelog.File)
		testastic.Equal(t, 2, len(cfg.Changelog.Include))
		testastic.Equal(t, "New Features", cfg.Changelog.Sections["feat"])
	})

	t.Run("config with custom bump types", func(t *testing.T) {
		t.Parallel()

		// given: a config with custom bump_types
		data, err := os.ReadFile("testdata/custom_bump_types/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(data)

		// then: bump types are parsed correctly
		testastic.NoError(t, err)
		testastic.SliceEqual(t, []string{"feat", "revert"}, cfg.BumpTypes.Minor)
		testastic.SliceEqual(t, []string{"fix", "perf", "docs"}, cfg.BumpTypes.Patch)
	})

	t.Run("config with changelog references", func(t *testing.T) {
		t.Parallel()

		// given: a config with changelog references
		data, err := os.ReadFile("testdata/changelog_references/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(data)

		// then: references are parsed correctly
		testastic.NoError(t, err)
		testastic.Equal(t, 2, len(cfg.Changelog.References.Patterns))
		testastic.Equal(t, `JIRA-\d+`, cfg.Changelog.References.Patterns[0].Pattern)
		testastic.Equal(t, "https://jira.example.com/browse/{value}", cfg.Changelog.References.Patterns[0].URL)
		testastic.Equal(t, `#\d+`, cfg.Changelog.References.Patterns[1].Pattern)
		testastic.Equal(t, "", cfg.Changelog.References.Patterns[1].URL)
		testastic.Equal(t, 2, len(cfg.Changelog.References.Footers))
		testastic.Equal(t, "https://jira.example.com/browse/{value}", cfg.Changelog.References.Footers["Refs"])
		testastic.Equal(t, "", cfg.Changelog.References.Footers["Closes"])
	})

	t.Run("invalid versioning", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid versioning strategy
		data, err := os.ReadFile("testdata/invalid_versioning/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("invalid target versioning", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid target-level versioning strategy
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:       config.TargetTypePath,
				Path:       ".",
				TagPrefix:  "v",
				Versioning: config.VersioningStrategy("calendar"),
			},
		}

		// when: validating the config
		err := cfg.Validate()

		// then: validation rejects the unsupported target versioning strategy
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.api.versioning")
	})

	t.Run("invalid provider", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid provider
		data, err := os.ReadFile("testdata/invalid_provider/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty string provider is invalid", func(t *testing.T) {
		t.Parallel()

		// given: config with the legacy empty-string provider value
		data, err := os.ReadFile("testdata/empty_provider/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty branch", func(t *testing.T) {
		t.Parallel()

		// given: config with empty branch
		data, err := os.ReadFile("testdata/empty_branch/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("invalid yaml", func(t *testing.T) {
		t.Parallel()

		// given: invalid YAML syntax
		data := []byte("release: [")

		// when: parsing the config
		_, err := config.Parse(data)

		// then: parsing fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("targets require explicit tag prefix", func(t *testing.T) {
		t.Parallel()

		// given: a target config without per-target tag prefix
		data, err := os.ReadFile("testdata/targets_missing_prefix/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(data)

		// then: target validation rejects the missing per-target prefix
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.api.tag_prefix must not be empty")
	})

	t.Run("explicit empty targets config is invalid", func(t *testing.T) {
		t.Parallel()

		// given: a YAML config that explicitly sets an empty targets map
		data, err := os.ReadFile("testdata/empty_targets/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = config.Parse(data)

		// then: validation rejects the empty targets block
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets must not be empty")
	})
}

func TestValidate(t *testing.T) {
	t.Parallel()

	t.Run("valid config passes", func(t *testing.T) {
		t.Parallel()

		// given: a valid default config with targets
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: no error
		testastic.NoError(t, err)
	})

	t.Run("empty changelog include fails", func(t *testing.T) {
		t.Parallel()

		// given: config with empty changelog include
		cfg := config.Default()
		cfg.Changelog.Include = nil

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty changelog file fails", func(t *testing.T) {
		t.Parallel()

		// given: config with empty changelog file
		cfg := config.Default()
		cfg.Changelog.File = ""

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("empty version file path fails", func(t *testing.T) {
		t.Parallel()

		// given: config with an empty version file path
		cfg := config.Default()
		cfg.VersionFiles = []string{"  "}

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("invalid auto merge method fails", func(t *testing.T) {
		t.Parallel()

		// given: config with unsupported auto merge method
		cfg := config.Default()
		cfg.Release.AutoMergeMethod = "fast-forward"

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("repository owner and repo must be set together", func(t *testing.T) {
		t.Parallel()

		// given: repository config with only owner set
		cfg := config.Default()
		cfg.Repository.Owner = "platform"

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("repository project must match owner and repo when both are set", func(t *testing.T) {
		t.Parallel()

		// given: repository config with conflicting explicit coordinates
		cfg := config.Default()
		cfg.Repository.Owner = "platform"
		cfg.Repository.Repo = "yeet"
		cfg.Repository.Project = "group/subgroup/service"

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.project must match repository.owner/repo")
	})

	t.Run("github project must stay in owner repo form", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with a subgroup-style project path
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.Project = "group/subgroup/service"

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.project must be in owner/repo form for github")
	})

	t.Run("github project in valid owner repo form passes", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with a valid two-segment project
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.Project = "owner/repo"
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate()

		// then: no error
		testastic.NoError(t, err)
	})

	t.Run("github project with empty owner segment fails", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with an empty owner segment
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.Project = "/repo"

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.project must be in owner/repo form for github")
	})

	t.Run("github project with empty repo segment fails", func(t *testing.T) {
		t.Parallel()

		// given: explicit github provider with an empty repo segment
		cfg := config.Default()
		cfg.Provider = config.ProviderGitHub
		cfg.Repository.Project = "owner/"

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "repository.project must be in owner/repo form for github")
	})

	t.Run("empty repository remote fails", func(t *testing.T) {
		t.Parallel()

		// given: repository config with an empty remote name
		cfg := config.Default()
		cfg.Repository.Remote = ""

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
	})

	t.Run("windows drive letter target path fails", func(t *testing.T) {
		t.Parallel()

		// given: a target with an absolute Windows-style path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "C:/repo/app",
				TagPrefix: "api-v",
			},
		}

		// when: validating the config
		err := cfg.Validate()

		// then: the repo-relative path validation rejects the absolute path
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be repo-relative")
	})

	t.Run("windows drive letter exclude path fails", func(t *testing.T) {
		t.Parallel()

		// given: a target with an absolute Windows-style exclude path
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"root": {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api", "D:/repo/shared"},
				Includes:     []string{"api"},
			},
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
		}

		// when: validating the config
		err := cfg.Validate()

		// then: the repo-relative path validation rejects the absolute exclude path
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "must be repo-relative")
	})

	t.Run("duplicate inherited version file across targets fails", func(t *testing.T) {
		t.Parallel()

		// given: multiple targets that inherit the same top-level version file path
		cfg := config.Default()
		cfg.VersionFiles = []string{"VERSION"}
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
				Changelog: config.ChangelogConfig{File: "services/api/CHANGELOG.md"},
			},
			"web": {
				Type:      config.TargetTypePath,
				Path:      "apps/web",
				TagPrefix: "web-v",
				Changelog: config.ChangelogConfig{File: "apps/web/CHANGELOG.md"},
			},
		}

		// when: validating the config
		err := cfg.Validate()

		// then: validation rejects the shared version file ownership before release time
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "version_files")
	})

	t.Run("overlapping bump types fails", func(t *testing.T) {
		t.Parallel()

		// given: config with a type appearing in both minor and patch
		cfg := config.Default()
		cfg.BumpTypes.Minor = []string{"feat"}
		cfg.BumpTypes.Patch = []string{"fix", "feat"}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "feat")
	})

	t.Run("empty string in bump types minor fails", func(t *testing.T) {
		t.Parallel()

		// given: config with an empty string in bump_types.minor
		cfg := config.Default()
		cfg.BumpTypes.Minor = []string{"feat", ""}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate()

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "bump_types.minor")
	})

	t.Run("empty bump types lists are valid", func(t *testing.T) {
		t.Parallel()

		// given: config with empty bump type lists
		cfg := config.Default()
		cfg.BumpTypes.Minor = []string{}
		cfg.BumpTypes.Patch = []string{}
		cfg.Targets = map[string]config.Target{
			"app": {Type: config.TargetTypePath, Path: ".", TagPrefix: "v"},
		}

		// when: validating
		err := cfg.Validate()

		// then: validation passes
		testastic.NoError(t, err)
	})
}

func TestBumpTypesConfig_ToBumpMapping(t *testing.T) {
	t.Parallel()

	t.Run("default config produces default mapping", func(t *testing.T) {
		t.Parallel()

		// given: default bump types config
		bt := config.BumpTypesConfig{
			Minor: []string{"feat"},
			Patch: []string{"fix", "perf"},
		}

		// when: converting to bump mapping
		mapping := bt.ToBumpMapping()

		// then: matches expected mapping
		testastic.Equal(t, 3, len(mapping))
		testastic.Equal(t, "minor", mapping["feat"])
		testastic.Equal(t, "patch", mapping["fix"])
		testastic.Equal(t, "patch", mapping["perf"])
	})

	t.Run("custom config produces custom mapping", func(t *testing.T) {
		t.Parallel()

		// given: custom bump types config
		bt := config.BumpTypesConfig{
			Minor: []string{"feat", "revert"},
			Patch: []string{"docs"},
		}

		// when: converting to bump mapping
		mapping := bt.ToBumpMapping()

		// then: matches expected mapping
		testastic.Equal(t, 3, len(mapping))
		testastic.Equal(t, "minor", mapping["feat"])
		testastic.Equal(t, "minor", mapping["revert"])
		testastic.Equal(t, "patch", mapping["docs"])
	})

	t.Run("empty config produces empty mapping", func(t *testing.T) {
		t.Parallel()

		// given: empty bump types config
		bt := config.BumpTypesConfig{}

		// when: converting to bump mapping
		mapping := bt.ToBumpMapping()

		// then: empty mapping
		testastic.Equal(t, 0, len(mapping))
	})
}

func TestResolvedTargets(t *testing.T) {
	t.Parallel()

	t.Run("resolves monorepo targets with inherited defaults", func(t *testing.T) {
		t.Parallel()

		// given: a monorepo config with path and derived targets
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"root": {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api"},
				Includes:     []string{"api"},
			},
		}

		// when: resolving targets
		resolvedTargets, err := cfg.ResolvedTargets()

		// then: target defaults and ownership data are expanded correctly
		testastic.NoError(t, err)
		testastic.Equal(t, "api-v", resolvedTargets["api"].TagPrefix)
		testastic.Equal(t, config.VersioningSemver, resolvedTargets["api"].Versioning)
		testastic.Equal(t, "CHANGELOG.md", resolvedTargets["root"].Changelog.File)
		testastic.SliceEqual(t, []string{"api"}, resolvedTargets["root"].Includes)
	})

	t.Run("normalizes target ids for lookup and includes", func(t *testing.T) {
		t.Parallel()

		// given: targets whose YAML IDs include surrounding whitespace
		cfg := config.Default()
		spacedAPIID := " api "
		spacedRootID := " root "
		cfg.Targets = map[string]config.Target{
			spacedAPIID: {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			spacedRootID: {
				Type:         config.TargetTypeDerived,
				Path:         ".",
				TagPrefix:    "v",
				ExcludePaths: []string{"services/api"},
				Includes:     []string{spacedAPIID},
			},
		}

		// when: resolving targets
		resolvedTargets, err := cfg.ResolvedTargets()

		// then: normalized IDs are used consistently
		testastic.NoError(t, err)
		testastic.Equal(t, "api", resolvedTargets["api"].ID)
		testastic.Equal(t, "root", resolvedTargets["root"].ID)
		testastic.SliceEqual(t, []string{"api"}, resolvedTargets["root"].Includes)
	})

	t.Run("rejects duplicate normalized target ids", func(t *testing.T) {
		t.Parallel()

		// given: two target IDs that normalize to the same value
		cfg := config.Default()
		spacedAPIID := " api "
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			spacedAPIID: {
				Type:      config.TargetTypePath,
				Path:      "services/api-alt",
				TagPrefix: "api-alt-v",
			},
		}

		// when: resolving targets
		_, err := cfg.ResolvedTargets()

		// then: validation rejects the duplicate logical ID
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "target IDs must be unique and non-empty")
	})

	t.Run("rejects overlapping direct ownership", func(t *testing.T) {
		t.Parallel()

		// given: two path targets that directly overlap
		cfg := config.Default()
		cfg.Targets = map[string]config.Target{
			"api": {
				Type:      config.TargetTypePath,
				Path:      "services/api",
				TagPrefix: "api-v",
			},
			"services": {
				Type:      config.TargetTypePath,
				Path:      "services",
				TagPrefix: "services-v",
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: ambiguous ownership is rejected
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "direct path ownership overlaps")
	})
}

func TestPreMajorOptions(t *testing.T) {
	t.Parallel()

	t.Run("parses explicit false at top level", func(t *testing.T) {
		t.Parallel()

		// given: a config with both pre-major options explicitly false
		data, err := os.ReadFile("testdata/pre_major_explicit_false/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := config.Parse(data)

		// then: both options are false
		testastic.NoError(t, err)
		testastic.False(t, cfg.PreMajorBreakingBumpsMinor)
		testastic.False(t, cfg.PreMajorFeaturesBumpPatch)
	})

	t.Run("target inherits top-level values", func(t *testing.T) {
		t.Parallel()

		// given: top-level options set to false, target does not override
		cfg := config.Default()
		cfg.PreMajorBreakingBumpsMinor = false
		cfg.PreMajorFeaturesBumpPatch = false
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets()

		// then: target inherits top-level values
		testastic.NoError(t, err)
		testastic.False(t, resolved["app"].PreMajorBreakingBumpsMinor)
		testastic.False(t, resolved["app"].PreMajorFeaturesBumpPatch)
	})

	t.Run("target overrides top-level true with false", func(t *testing.T) {
		t.Parallel()

		// given: top-level defaults are true, target sets false
		cfg := config.Default()
		breakingFalse := false
		featuresFalse := false
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                       config.TargetTypePath,
				Path:                       ".",
				TagPrefix:                  "v",
				PreMajorBreakingBumpsMinor: &breakingFalse,
				PreMajorFeaturesBumpPatch:  &featuresFalse,
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets()

		// then: target overrides with false
		testastic.NoError(t, err)
		testastic.False(t, resolved["app"].PreMajorBreakingBumpsMinor)
		testastic.False(t, resolved["app"].PreMajorFeaturesBumpPatch)
	})

	t.Run("target overrides top-level false with true", func(t *testing.T) {
		t.Parallel()

		// given: top-level set to false, target overrides with true
		cfg := config.Default()
		cfg.PreMajorBreakingBumpsMinor = false
		cfg.PreMajorFeaturesBumpPatch = false
		breakingTrue := true
		featuresTrue := true
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                       config.TargetTypePath,
				Path:                       ".",
				TagPrefix:                  "v",
				PreMajorBreakingBumpsMinor: &breakingTrue,
				PreMajorFeaturesBumpPatch:  &featuresTrue,
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets()

		// then: target overrides with true
		testastic.NoError(t, err)
		testastic.True(t, resolved["app"].PreMajorBreakingBumpsMinor)
		testastic.True(t, resolved["app"].PreMajorFeaturesBumpPatch)
	})

	t.Run("target inherits top-level references and merges overrides", func(t *testing.T) {
		t.Parallel()

		// given: top-level references with patterns and footers, target adds a footer override
		cfg := config.Default()
		cfg.Changelog.References = config.ReferencesConfig{
			Patterns: []config.ReferencePattern{
				{Pattern: `JIRA-\d+`, URL: "https://jira.example.com/browse/{value}"},
			},
			Footers: map[string]string{
				"Refs": "https://jira.example.com/browse/{value}",
			},
		}
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				Changelog: config.ChangelogConfig{
					References: config.ReferencesConfig{
						Footers: map[string]string{
							"Closes": "",
						},
					},
				},
			},
		}

		// when: resolving targets
		resolved, err := cfg.ResolvedTargets()

		// then: target inherits top-level patterns (no override) and merges footers
		testastic.NoError(t, err)
		testastic.Equal(t, 1, len(resolved["app"].Changelog.References.Patterns))
		testastic.Equal(t, `JIRA-\d+`, resolved["app"].Changelog.References.Patterns[0].Pattern)
		testastic.Equal(t, 2, len(resolved["app"].Changelog.References.Footers))
		testastic.Equal(t, "https://jira.example.com/browse/{value}", resolved["app"].Changelog.References.Footers["Refs"])
		testastic.Equal(t, "", resolved["app"].Changelog.References.Footers["Closes"])
	})

	t.Run("rejects pre_major_breaking_bumps_minor on calver target", func(t *testing.T) {
		t.Parallel()

		// given: a calver target with explicit pre_major_breaking_bumps_minor
		cfg := config.Default()
		breakingTrue := true
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                       config.TargetTypePath,
				Path:                       ".",
				TagPrefix:                  "v",
				Versioning:                 config.VersioningCalVer,
				PreMajorBreakingBumpsMinor: &breakingTrue,
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: error mentions the incompatibility
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "pre_major_breaking_bumps_minor")
		testastic.ErrorContains(t, err, "calver")
	})

	t.Run("rejects pre_major_features_bump_patch on calver target", func(t *testing.T) {
		t.Parallel()

		// given: a calver target with explicit pre_major_features_bump_patch
		cfg := config.Default()
		featuresFalse := false
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:                      config.TargetTypePath,
				Path:                      ".",
				TagPrefix:                 "v",
				Versioning:                config.VersioningCalVer,
				PreMajorFeaturesBumpPatch: &featuresFalse,
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: error mentions the incompatibility
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "pre_major_features_bump_patch")
		testastic.ErrorContains(t, err, "calver")
	})

	t.Run("allows calver target without pre_major overrides", func(t *testing.T) {
		t.Parallel()

		// given: a calver target that inherits pre_major options (does not set them)
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: no error — inherited options are silently ignored
		testastic.NoError(t, err)
	})

	t.Run("rejects invalid top-level calver format", func(t *testing.T) {
		t.Parallel()

		// given: a config with an unsupported calver format
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.CalVer.Format = "YYYY.QQ.MICRO"
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: validation fails before release planning
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "calver.format")
	})

	t.Run("rejects invalid target calver format", func(t *testing.T) {
		t.Parallel()

		// given: a target with an unsupported calver format override
		cfg := config.Default()
		cfg.Versioning = config.VersioningCalVer
		cfg.Targets = map[string]config.Target{
			"app": {
				Type:      config.TargetTypePath,
				Path:      ".",
				TagPrefix: "v",
				CalVer: config.CalVerConfig{
					Format: "YYYY.0M",
				},
			},
		}

		// when: validating
		err := cfg.Validate()

		// then: validation fails with the target path
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, config.ErrInvalidConfig)
		testastic.ErrorContains(t, err, "targets.app.calver.format")
	})
}
