package config //nolint:testpackage // exercises unexported parse and load directly

import (
	"context"
	"os"
	"testing"
	"time"

	"github.com/monkescience/testastic"
)

func TestParse(t *testing.T) {
	t.Parallel()

	t.Run("valid minimal config", func(t *testing.T) {
		t.Parallel()

		// given: a minimal YAML config
		data, err := os.ReadFile("testdata/minimal/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: it succeeds with defaults filled in
		testastic.NoError(t, err)
		testastic.Equal(t, VersioningSemver, cfg.Versioning)
		testastic.Equal(t, "main", cfg.Branch)
	})

	t.Run("config with prerelease channels", func(t *testing.T) {
		t.Parallel()

		// given: a config with a prerelease channel
		data, err := os.ReadFile("testdata/prerelease_channels/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: channel settings are parsed and validated
		testastic.NoError(t, err)
		testastic.Equal(t, "beta", cfg.Release.Channels["beta"].Branch)
		testastic.Equal(t, "beta", cfg.Release.Channels["beta"].Prerelease)
	})

	t.Run("partial release labels preserve defaults", func(t *testing.T) {
		t.Parallel()

		// given: a config overriding only the pending lifecycle label
		data := []byte("release:\n  labels:\n    pending: 'release: waiting'\n" +
			"targets:\n  app:\n    type: path\n    path: .\n    tag_prefix: v\n")

		// when: parsing the config over defaults
		cfg, err := parse(data)

		// then: the partial object retains the tagged default
		testastic.NoError(t, err)
		testastic.Equal(t, "release: waiting", cfg.Release.Labels.Pending)
		testastic.Equal(t, "autorelease: tagged", cfg.Release.Labels.Tagged)
		testastic.True(t, cfg.Release.Labels.Yeet)
	})

	t.Run("managed yeet label can be disabled", func(t *testing.T) {
		t.Parallel()

		// given: a config opting out of the managed yeet label
		data := []byte("release:\n  labels:\n    yeet: false\n" +
			"targets:\n  app:\n    type: path\n    path: .\n    tag_prefix: v\n")

		// when: parsing the config over defaults
		cfg, err := parse(data)

		// then: the managed label is disabled without changing lifecycle defaults
		testastic.NoError(t, err)
		testastic.False(t, cfg.Release.Labels.Yeet)
		testastic.Equal(t, "autorelease: pending", cfg.Release.Labels.Pending)
		testastic.Equal(t, "autorelease: tagged", cfg.Release.Labels.Tagged)
	})

	t.Run("rejects removed subject include branch setting", func(t *testing.T) {
		t.Parallel()

		// given: a config using the removed title toggle
		data := []byte("release:\n  subject_include_branch: true\n" +
			"targets:\n  app:\n    type: path\n    path: .\n    tag_prefix: v\n")

		// when: parsing the config
		_, err := parse(data)

		// then: strict parsing directs users away from the obsolete setting
		testastic.Error(t, err)
		testastic.ErrorContains(t, err, "subject_include_branch")
	})

	t.Run("valid full config", func(t *testing.T) {
		t.Parallel()

		// given: a full YAML config
		data, err := os.ReadFile("testdata/full/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: all values are set correctly
		testastic.NoError(t, err)
		testastic.Equal(t, VersioningCalVer, cfg.Versioning)
		testastic.Equal(t, "develop", cfg.Branch)
		testastic.Equal(t, ProviderGitLab, cfg.Provider)
		testastic.Equal(t, "upstream", cfg.Repository.Remote)
		testastic.NotNil(t, cfg.Repository.GitLab)
		testastic.Equal(t, "gitlab.company.com", cfg.Repository.GitLab.Host)
		testastic.Equal(t, "group/subgroup/service", cfg.Repository.GitLab.Project)
		testastic.Equal(t, 45*time.Second, cfg.Network.RequestTimeout)
		testastic.Equal(t, 6, cfg.Network.Retry.MaxAttempts)
		testastic.Equal(t, 2*time.Second, cfg.Network.Retry.MinBackoff)
		testastic.Equal(t, 20*time.Second, cfg.Network.Retry.MaxBackoff)
		testastic.Equal(t, "automation/release-{{ .Branch }}", cfg.Release.BranchTemplate)
		testastic.Equal(t, 500*time.Millisecond, cfg.Release.MergePolling.InitialInterval)
		testastic.Equal(t, 8*time.Second, cfg.Release.MergePolling.MaxInterval)
		testastic.Equal(t, 3*time.Minute, cfg.Release.MergePolling.Timeout)
		testastic.Equal(t, "release {{ .Tag }}", cfg.Release.PRTitle)
		testastic.Equal(t, "release {{ .TargetCount }} targets", cfg.Release.PRTitleGroup)
		testastic.Equal(t, "commit {{ .Tag }}", cfg.Release.CommitSubject)
		testastic.Equal(t, "commit {{ .TargetCount }} targets", cfg.Release.CommitSubjectGroup)
		testastic.True(t, cfg.Release.AutoMerge)
		testastic.True(t, cfg.Release.AutoMergeForce)
		testastic.Equal(t, AutoMergeMethodRebase, cfg.Release.AutoMergeMethod)
		testastic.Equal(t, "## Release checklist\n- [ ] smoke test", cfg.Release.PRBodyHeader)
		testastic.Equal(t, "_Generated by automation_", cfg.Release.PRBodyFooter)
		testastic.Equal(t, 3000, cfg.Release.PRBodyMaxLength)
		testastic.Equal(t, 2, len(cfg.VersionFiles))
		testastic.Equal(t, "VERSION", cfg.VersionFiles[0].Path)
		testastic.Equal(t, "CHANGES.md", cfg.Changelog.File)
		testastic.Equal(t, 2, len(cfg.Changelog.Include))
		testastic.Equal(t, "New Features", cfg.Changelog.Sections["feat"])
	})

	t.Run("config with json version file", func(t *testing.T) {
		t.Parallel()

		// given: a config that uses an explicit JSON version file entry
		data, err := os.ReadFile("testdata/json_version_file/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: the JSON entry is parsed with its explicit pointer
		testastic.NoError(t, err)
		testastic.Equal(t, 1, len(cfg.VersionFiles))
		testastic.Equal(t, "package.json", cfg.VersionFiles[0].Path)
		testastic.Equal(t, VersionFileFormatJSON, cfg.VersionFiles[0].Format)
		testastic.Equal(t, "/version", cfg.VersionFiles[0].JSONPointer)
	})

	t.Run("json version file requires json pointer", func(t *testing.T) {
		t.Parallel()

		// given: a JSON version file entry without an explicit pointer
		data, err := os.ReadFile("testdata/json_version_file_missing_pointer/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: validation rejects the ambiguous JSON entry
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(t, "invalid config: version_files json_pointer is required for format \"json\"", err.Error())
	})

	t.Run("config with custom bump types", func(t *testing.T) {
		t.Parallel()

		// given: a config with custom bump_types
		data, err := os.ReadFile("testdata/custom_bump_types/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: bump types are parsed correctly
		testastic.NoError(t, err)
		testastic.SliceEqual(t, []string{"feat", "revert"}, cfg.BumpTypes.Minor)
		testastic.SliceEqual(t, []string{"fix", "perf", "docs"}, cfg.BumpTypes.Patch)
	})

	t.Run("config with changelog references", func(t *testing.T) {
		t.Parallel()

		// given: a config with changelog references
		data, err := os.ReadFile("testdata/changelog_references/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: references are parsed correctly
		testastic.NoError(t, err)
		testastic.Equal(t, 2, len(cfg.Changelog.References.Patterns))
		testastic.Equal(t, `JIRA-\d+`, cfg.Changelog.References.Patterns[0].Pattern)
		testastic.Equal(t, "https://jira.example.com/browse/{value}", cfg.Changelog.References.Patterns[0].URL)
		testastic.Equal(t, `#\d+`, cfg.Changelog.References.Patterns[1].Pattern)
		testastic.Equal(t, "", cfg.Changelog.References.Patterns[1].URL)
		testastic.Equal(t, 2, len(cfg.Changelog.References.Footers))
		testastic.Equal(t, "https://jira.example.com/browse/{value}", cfg.Changelog.References.Footers["Refs"])
		testastic.Equal(t, "", cfg.Changelog.References.Footers["Closes"])
	})

	t.Run("invalid versioning", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid versioning strategy
		data, err := os.ReadFile("testdata/invalid_versioning/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
	})

	t.Run("invalid target versioning", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid target-level versioning strategy
		cfg := Default()
		cfg.Targets = map[string]Target{
			"api": {
				Type:       TargetTypePath,
				Path:       ".",
				TagPrefix:  "v",
				Versioning: VersioningStrategy("calendar"),
			},
		}

		// when: validating the config
		err := cfg.Validate()

		// then: validation rejects the unsupported target versioning strategy
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(
			t,
			"invalid config: targets.api.versioning must be \"semver\" or \"calver\", got \"calendar\"",
			err.Error(),
		)
	})

	t.Run("invalid provider", func(t *testing.T) {
		t.Parallel()

		// given: config with invalid provider
		data, err := os.ReadFile("testdata/invalid_provider/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
	})

	t.Run("empty string provider is invalid", func(t *testing.T) {
		t.Parallel()

		// given: config with the legacy empty-string provider value
		data, err := os.ReadFile("testdata/empty_provider/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
	})

	t.Run("empty branch", func(t *testing.T) {
		t.Parallel()

		// given: config with empty branch
		data, err := os.ReadFile("testdata/empty_branch/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: validation fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
	})

	t.Run("repository sub-section must match provider", func(t *testing.T) {
		t.Parallel()

		// given: provider github with a gitlab sub-section
		data, err := os.ReadFile("testdata/invalid_repository_wrong_subsection/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: parsing rejects the mismatched sub-section
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(t, "invalid config: repository.gitlab set but provider is github", err.Error())
	})

	t.Run("provider auto rejects any repository sub-section", func(t *testing.T) {
		t.Parallel()

		// given: provider auto plus a github sub-section
		data, err := os.ReadFile("testdata/invalid_repository_auto_with_subsection/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: parsing rejects the sub-section under auto
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(
			t,
			"invalid config: repository.github set but provider is auto. Set an explicit provider",
			err.Error(),
		)
	})

	t.Run("azuredevops happy path parses and hydrates", func(t *testing.T) {
		t.Parallel()

		// given: provider azuredevops with a fully-populated sub-section
		data, err := os.ReadFile("testdata/valid_repository_azuredevops/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: parse succeeds and flat fields are hydrated from the sub-section
		testastic.NoError(t, err)
		testastic.Equal(t, ProviderAzureDevOps, cfg.Provider)
		testastic.NotNil(t, cfg.Repository.AzureDevOps)
		testastic.Equal(t, "dev.azure.com", cfg.Repository.AzureDevOps.Host)
		testastic.Equal(t, "contoso", cfg.Repository.AzureDevOps.Organization)
		testastic.Equal(t, "MyProject", cfg.Repository.AzureDevOps.Project)
		testastic.Equal(t, "yeet", cfg.Repository.AzureDevOps.Repo)
		testastic.Equal(t, "DefaultCollection", cfg.Repository.AzureDevOps.Collection)
	})

	t.Run("invalid yaml", func(t *testing.T) {
		t.Parallel()

		// given: invalid YAML syntax
		data := []byte("release: [")

		// when: parsing the config
		_, err := parse(data)

		// then: parsing fails
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
	})

	t.Run("targets require explicit tag prefix", func(t *testing.T) {
		t.Parallel()

		// given: a target config without per-target tag prefix
		data, err := os.ReadFile("testdata/targets_missing_prefix/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: target validation rejects the missing per-target prefix
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(t, "invalid config: targets.api.tag_prefix must not be empty", err.Error())
	})

	t.Run("target tag prefix validation precedes versioning", func(t *testing.T) {
		t.Parallel()

		// given: a target with both an empty tag prefix and invalid versioning
		data := []byte(`versioning: semver
branch: main
targets:
  api:
    type: path
    path: services/api
    versioning: broken
`)

		// when: parsing the config
		_, err := parse(data)

		// then: the missing required prefix is reported first
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(t, "invalid config: targets.api.tag_prefix must not be empty", err.Error())
	})

	t.Run("explicit empty targets config is invalid", func(t *testing.T) {
		t.Parallel()

		// given: a YAML config that explicitly sets an empty targets map
		data, err := os.ReadFile("testdata/empty_targets/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		_, err = parse(data)

		// then: validation rejects the empty targets block
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(t, "invalid config: targets must not be empty", err.Error())
	})

	t.Run("parses explicit false at top level", func(t *testing.T) {
		t.Parallel()

		// given: a config with both pre-major options explicitly false
		data, err := os.ReadFile("testdata/pre_major_explicit_false/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: both options are false
		testastic.NoError(t, err)
		testastic.False(t, cfg.PreMajorBreakingBumpsMinor)
		testastic.False(t, cfg.PreMajorFeaturesBumpPatch)
	})
}

func TestLoad(t *testing.T) {
	t.Parallel()

	t.Run("missing file returns wrapped read error", func(t *testing.T) {
		t.Parallel()

		// given: a path that does not exist
		path := "testdata/does_not_exist.yaml"

		// when: loading the config
		_, err := load(context.Background(), path)

		// then: load returns a contextual error
		testastic.Error(t, err)
		testastic.Equal(
			t,
			"read config file testdata/does_not_exist.yaml: open testdata/does_not_exist.yaml: no "+
				"such file or directory",
			err.Error(),
		)
	})

	t.Run("loads valid file from disk", func(t *testing.T) {
		t.Parallel()

		// given: a path to a known-good fixture
		path := "testdata/minimal/input.yaml"

		// when: loading the config
		cfg, err := load(context.Background(), path)

		// then: it succeeds
		testastic.NoError(t, err)
		testastic.Equal(t, VersioningSemver, cfg.Versioning)
	})
	t.Run("parses reviewers from yaml", func(t *testing.T) {
		t.Parallel()

		// given: a config with release reviewers
		data, err := os.ReadFile("testdata/release_reviewers/input.yaml")
		testastic.NoError(t, err)

		// when: parsing the config
		cfg, err := parse(data)

		// then: reviewers are parsed in order
		testastic.NoError(t, err)
		testastic.SliceEqual(t, []string{"alice", "bob"}, cfg.Release.Reviewers)
	})
}

func TestParseReleaseReviewers(t *testing.T) {
	t.Parallel()

	reviewersConfig := func(entries string) []byte {
		return []byte("release:\n  reviewers:\n" + entries +
			"targets:\n  app:\n    type: path\n    path: .\n    tag_prefix: v\n")
	}

	t.Run("whitespace-padded reviewer fails", func(t *testing.T) {
		t.Parallel()

		// given: a config with a reviewer that has trailing whitespace
		data := reviewersConfig("    - \"alice \"\n")

		// when: parsing the config
		_, err := parse(data)

		// then: validation fails naming the padded entry
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(
			t,
			"invalid config: release.reviewers entry \"alice \" must not have leading or trailing "+
				"whitespace",
			err.Error(),
		)
	})

	t.Run("duplicate reviewer after trimming fails", func(t *testing.T) {
		t.Parallel()

		// given: a config with the same reviewer once padded and once plain
		data := reviewersConfig("    - \"alice\"\n    - \" alice\"\n")

		// when: parsing the config
		_, err := parse(data)

		// then: validation fails (the padded entry is rejected outright)
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
	})

	t.Run("duplicate reviewer fails", func(t *testing.T) {
		t.Parallel()

		// given: a config with a duplicated reviewer
		data := reviewersConfig("    - \"alice\"\n    - \"alice\"\n")

		// when: parsing the config
		_, err := parse(data)

		// then: validation fails naming the duplicate
		testastic.Error(t, err)
		testastic.ErrorIs(t, err, ErrInvalidConfig)
		testastic.Equal(t, "invalid config: release.reviewers contains duplicate \"alice\"", err.Error())
	})
}
